services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docmind_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/chroma_db:/app/chroma_db
